### ISSUE TITLE
I can not understand the difference between "PDFViewPagerIVZoom" and "PDFViewPager"

### ISSUE THREAD

**Issue by IdioticMadman** [voghDev/PdfViewPager#10]
From the code
```Java
public class PDFViewPagerIVZoom extends PDFViewPager {
    public PDFViewPagerIVZoom(Context context, String pdfPath) {
        super(context, pdfPath);
    }

    public PDFViewPagerIVZoom(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    protected void initAdapter(Context context, String pdfPath){
        setAdapter(new PDFPagerAdapter(context, pdfPath, getOffscreenPageLimit()));
    }
}
```
All method in **PDFViewPagerIVZoom ** are inherited from **PDFViewPager **.

**Comment by voghDev** [comment]
Hello,

PDFViewPagerIVZoom is the legacy implementation using ImageViewZoom library. It should have an adapter with ImageViewZoom, called LegacyPDFPagerAdapter.

It does in the last version of the repo:

    public class PDFViewPagerIVZoom extends PDFViewPager {
        public PDFViewPagerIVZoom(Context context, String pdfPath) {
            super(context, pdfPath);
        }

        public PDFViewPagerIVZoom(Context context, AttributeSet attrs) {
            super(context, attrs);
        }

        protected void initAdapter(Context context, String pdfPath){
            setAdapter(new LegacyPDFPagerAdapter(context, pdfPath, getOffscreenPageLimit()));
        }
    }

Probably you are seeing an old version of the code, where I forgot to change the adapter. Thanks for noticing :)

**Comment by voghDev** [comment]
Legacy classes such as PDFVIewPagerIVZoom are going to be deprecated in future versions. I'll close the issue because this difference is not gonna exist anymore.
