### ISSUE TITLE
change the smallest zoom level will crash on accidental

### ISSUE THREAD

**Issue by JichunMa** [voghDev/PdfViewPager#100]
```
    E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abc.debug, PID: 3292
    java.lang.IllegalArgumentException: pointerIndex out of range
```
maybe it crash because of zoom in viewpager. And the issue was occur in the ViewPager source code. But I found a solution for it.  Just try catch for it~
[bugs detail](https://stackoverflow.com/questions/16459196/java-lang-illegalargumentexception-pointerindex-out-of-range-exception-dispat)

**Comment by voghDev** [comment]
Hi,

same issue as #71, #43, #14, #19. Btw last version of the library is not using PhotoView library anymore, so you shouldn't get this error with it.

Anyway you have the solution on these issues :)
