### ISSUE TITLE
How to change it into a vertical column

### ISSUE THREAD

**Issue by shiner0** [voghDev/PdfViewPager#104]
compile 'es.voghdev.pdfviewpager:library:1.0.3'

**Comment by voghDev** [comment]
Hi,

can you translate the title to English please?

**Comment by shiner0** [comment]
> 嗨，
> 
> 你能把标题翻译成英文吗？

How to change it into a vertical column

**Comment by voghDev** [comment]
You probably need the `VerticalViewPager` class. See issues #46, #31, #7

**Comment by voghDev** [comment]
Hi,

there is an updated version of the `vertical_viewpager` branch

You can try it using

`implementation 'es.voghdev.pdfviewpager:library:1.1.3'`

Let me know if it's useful for you
