### ISSUE TITLE
Not working in Android Studio 3.4 

### ISSUE THREAD

**Issue by MavyaSoni** [voghDev/PdfViewPager#106]
while using 
implementation 'es.voghdev.pdfviewpager:library:1.0.5'

This is not working with new Android Studio 3.4

As per your documents in GitHub. It is using compile 'es.voghdev.pdfviewpager:library:1.0.5'
but  compile is deprecated now in new Android studio 3.4

**Comment by voghDev** [comment]
Fixed in v1.0.6

You can now import

    implementation 'es.voghdev.pdfviewpager:library:1.0.6'
