### ISSUE TITLE
Add support for AndroidX ViewPager

### ISSUE THREAD

**Issue by tevjef** [voghDev/PdfViewPager#108]
Since work on the `android.support.v4.view.ViewPager` has been halted in favor of AndroidX this library will not be able to take advantage of potential bug fixes in the future. 

Additionally, since this library is using legacy ViewPager, Android Gradle Plugin 3.2+  will flag it to be "jetified", a process where the bytecode of the library will be rewritten to use the new AndroidX View Pager. To avoid this it is recommended that this library is updated to used AndroidX's version of ViewPager. 

 `PDFViewPager` extends `ViewPager` and parts `ViewPager` public API is part of `PDFViewPager`'s public API, as such usage of `PDFViewPager` will be shown as errors in Android Studio. 

![screen shot 2018-12-06 at 12 23 24 pm](https://user-images.githubusercontent.com/1676418/49600745-e84fa100-f951-11e8-9f30-7d4ad6f1cee4.png)

More information can be found here: https://developer.android.com/jetpack/androidx/migrate

If you need help with this migration, I would be happy to help in any way I can!

**Comment by anudeepreddygopu** [comment]
Any plans to give support for AndroidX?

**Comment by voghDev** [comment]
Yes, I'm planning to support it. Won't have time this christmas, but I will start implementing this as soon as I get some time to dedicate

**Comment by voghDev** [comment]
Hi guys!

you can now use version `1.1.0` of the library which supports `androidx.ViewPager`. Sorry for the delay, but I've been pretty busy at work, conferences and events :)

Better late than never!
