### ISSUE TITLE
Problem compiling class

### ISSUE THREAD

**Issue by Albertorio** [voghDev/PdfViewPager#11]
After adding "compile 'es.voghdev.pdfviewpager:library:0.3.0" to my app, when I try to sync the gradle files I get the following error. 

Error:Execution failed for task ':app:processDebugManifest'.
Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:11:9-43	is also present at [es.voghdev.pdfviewpager:library:0.3.0] AndroidManifest.xml:13:9-49 value=(@drawable/ic_pdfviewpager).
Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:9:5-35:19 to override.

**Comment by voghDev** [comment]
I forgot to remove the application icon, sorry for that. 

Add the tools:replace line to your <application> element in the AndroidManifest.xml file, like this:

    <application
            android:allowBackup="true"
            android:icon="@drawable/ic_launcher"
            android:label="@string/app_name"
            android:theme="@style/AppTheme"
            tools:replace="android:icon"
            android:name=".global.YourApplicationClassName">

Then try to recompile

**Comment by Albertorio** [comment]
Now its working, thank you!
