### ISSUE TITLE
Is it possible to rename PDF file?

### ISSUE THREAD

**Issue by Zookey** [voghDev/PdfViewPager#115]
Hi, 

I would like to rename PDF file that library downloads to the destination path.

Is it possible with this library?

**Comment by voghDev** [comment]
Hello,

Yes it is. 
By default the library uses [this DownloadFile implementation](https://github.com/voghDev/PdfViewPager/blob/master/library/src/main/java/es/voghdev/pdfviewpager/library/remote/DownloadFileUrlConnectionImpl.java) that you can extend or modify to suit your needs.

As you can see [here](https://github.com/voghDev/PdfViewPager/blob/master/library/src/main/java/es/voghdev/pdfviewpager/library/RemotePDFViewPager.java), you have a constructor where you can pass your own (modified) DownloadFile dependency, so in this one you can rename the downloaded file to whatever name you need.

Hope this helps

**Comment by Zookey** [comment]
Thanks for the response. Your advice helped me a lot.
