### ISSUE TITLE
Handling a click on the viewpager object.

### ISSUE THREAD

**Issue by Mucore** [voghDev/PdfViewPager#12]
First of all, really cool widget. Easy to implement and not too complicated. 
What I would like to know is can you set a click listener (A single regular click/tap) to the pdfviewpager. Current page position/number doesn't matter.

I attempted attaching a regular onClickListener and an onTouchListener (with MotionEvents). But both didn't work.

Some help would be great!
Thanks a lot!

**Comment by voghDev** [comment]
Hi,

I haven't tried to implement this feature. Maybe I can think about a mechanism such as a Listener that can be fired on each page's tap, but this pattern (single tap on a PDF) sounds a bit strange.

Can you describe a little bit what you're trying to do? Maybe you can add a button somewhere else for the feature you want on Click, or similar.

**Comment by Mucore** [comment]
My app opens the PDF in full screen view by default. I want the Navbar and the bottom control panel to toggle whenever the user just taps on the document. 

Right now I use a button between the lower edge of the screen and the lower edge of the ViewPager to accomplish this. I just wanted to know if it's possible to do it with a tap to the document, 'cause this looks awkward.

**Comment by voghDev** [comment]
I see,

let me think a clean solution and i'll add some listener that you can override for a single tap at least.

**Comment by Mucore** [comment]
Nice! Thank you very much!

**Comment by voghDev** [comment]
Hi,

version 1.0.1 released. You can now instantiate a PdfPagerAdapter with the code shown on the previous comment and capture the OnPageClick event.
