### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by bruse1990** [voghDev/PdfViewPager#13]
Remote PDF's from a URL 

when the pdf page more than 50 ,out of memory

**Comment by voghDev** [comment]
Which version of the library are you using?

**Comment by bruse1990** [comment]
compile 'es.voghdev.pdfviewpager:library:0.3.0'

**Comment by voghDev** [comment]
That's strange. The PDF in samples (moby.pdf) has got 1048 pages and does not cause OutOfMemoryError. Is your PDF file public or available somewhere?

Anyway, I suggest you to generate a PDF document with less pages, just for usability. No one is gonna read 56 pages inside your app, so maybe you can cut it to the 5-10 most useful ones.

**Comment by bruse1990** [comment]
http://qlzqzg.com/upload/project/2015-12-10-103233-%E9%BD%90%E9%B2%81%E7%A8%B3%E5%9B%BA21%E5%A4%A9%E9%9B%86%E5%90%88%E8%B5%84%E4%BA%A7%E7%AE%A1%E7%90%86%E8%AE%A1%E5%88%92%E7%AE%A1%E7%90%86%E5%90%88%E5%90%8C20151202.pdf

this address can you visit

**Comment by justdeko** [comment]
@voghDev not trying to reopen the issue, but is there a way to clear the cache or wherever the downloaded pdf files are stored? I also get the issue after opening documents several times because apparently they dont get overwritten and just pile up.

**Comment by voghDev** [comment]
What do you mean with dont get overwritten? Do you want to download the PDF files more than once?
You can use `getCacheDir()` from `Context` class to remove any previously downloaded pdf file. Just use `listFiles` method and remove the ones you need.

Is that what you mean with clearing the cache?

**Comment by justdeko** [comment]
Yes, that is indeed what I need. Thanks a lot! :)

**Comment by voghDev** [comment]
You're welcome ;)
