### ISSUE TITLE
SecurityException

### ISSUE THREAD

**Issue by haisiva03** [voghDev/PdfViewPager#135]
Your library file cannot open password protected file.if i  open password protected file its through 
java.lang.SecurityException: password required or incorrect password (Exception).

Add the function or method to open password protected file

**Comment by voghDev** [comment]
Hello man,

do you have sample code on how to open a password protected file?
Once the file is open, you should be able to pass it to the library.

**Comment by haisiva03** [comment]
> Hello man,
> 
> do you have sample code on how to open a password protected file?
> Once the file is open, you should be able to pass it to the library.

hi voghDev , i don't have any code...i found some other library have function to pass password to their library but your library file don't have that method or function.. even i am not interested to use other library because your quite simple and lite weight....can you help me  how to pass password in your library....

**Comment by voghDev** [comment]
Ok!
I think that opening a password-protected file is not `PdfViewPager`'s responsibility. `PdfViewPager` is just a document renderer, and the PDF file you pass to it should be available for reading.
So if the PDF file needs to disable some password protection before reading it, I think an external actor should be responsible for that :)

Feel free to fork the repository, clone the code, and modify anything you need for your own requirements

**Comment by DamienEllis** [comment]
Hi there i need some assistance regarding this password protected problem, how would i unlock the file, before i pass it to get rendered in to view?
