### ISSUE TITLE
How to give custom file name for remote download PDFs?

### ISSUE THREAD

**Issue by urvish91** [voghDev/PdfViewPager#138]

**Comment by voghDev** [comment]
Hi!

I think I understand what you want to do.

As you can see in [DownloadFile](https://github.com/voghDev/PdfViewPager/blob/master/library/src/main/java/es/voghdev/pdfviewpager/library/remote/DownloadFile.java) interface, and its [implementor class](https://github.com/voghDev/PdfViewPager/blob/master/library/src/main/java/es/voghdev/pdfviewpager/library/remote/DownloadFileUrlConnectionImpl.java), you can set the destination path of your choice (including your custom file name), and the downloaded file will be written there:

```
File file = new File(destinationPath);
FileOutputStream fileOutput = new FileOutputStream(file);
```

Hope it is helpful for you! :)
