### ISSUE TITLE
Android Api 29

### ISSUE THREAD

**Issue by tofigh77** [voghDev/PdfViewPager#139]
hi 
PdfViewPager not working in android 10 !!!!!!!
please help me

**Comment by tofigh77** [comment]
this problem is not abut this library.
in android 10 you cant create file like always 
if you want create file in android 10 like other android apis you must add  android:requestLegacyExternalStorage="true" in your manifest/application

**Comment by voghDev** [comment]
Hi!

Glad you found the root cause :) thanks for your contribution
