### ISSUE TITLE
Zoomin out PDF showing error 

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [voghDev/PdfViewPager#14]
showing this error when zooming pdf out pls help 
same error find here [https://github.com/chrisbanes/PhotoView/issues](url)
Process: com.pdffilereader,
  java.lang.IllegalArgumentException: pointerIndex out of range
  at android.view.MotionEvent.nativeGetAxisValue(Native Method)
  at android.view.MotionEvent.getX(MotionEvent.java:2057)

**Comment by sunil-singh-chaudhary** [comment]
Solve By making my on PDFviewpager class and use this code may other help this


public class PDFViewPager extends android.support.v4.view.ViewPager {
    protected Context context;

    public PDFViewPager(Context context, String pdfPath) {
        super(context);
        this.context = context;
        init(pdfPath);
    }

    public PDFViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
        this.context = context;
        init(attrs);
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        try {
            return super.onTouchEvent(ev);
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        return false;
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            return super.onInterceptTouchEvent(ev);
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        return false;
    }

    protected void init(String pdfPath) {
        initAdapter(context, pdfPath);
    }

    protected void init(AttributeSet attrs) {
        if (isInEditMode()) {
            setBackgroundResource(es.voghdev.pdfviewpager.library.R.drawable.flaticon_pdf_dummy);
            return;
        }

        if (attrs != null) {
            TypedArray a;

            a = context.obtainStyledAttributes(attrs, es.voghdev.pdfviewpager.library.R.styleable.PDFViewPager);
            String assetFileName = a.getString(es.voghdev.pdfviewpager.library.R.styleable.PDFViewPager_assetFileName);

            if (assetFileName != null && assetFileName.length() > 0)
                initAdapter(context, assetFileName);
        }
    }

    protected void initAdapter(Context context, String pdfPath) {
        setAdapter(new PDFPagerAdapter(context, pdfPath, getOffscreenPageLimit()));
    }
}

**Comment by voghDev** [comment]
Hello,

this is a known issue of [photoview](https://github.com/chrisbanes/PhotoView) library.

You can use [PdfViewPagerZoom](https://github.com/voghDev/PdfViewPager/blob/master/library/src/main/java/es/voghdev/pdfviewpager/library/PDFViewPagerZoom.java) which implements the error handler you made. Your implementation is also correct, though it repeats code and is less maintainable.

Thanks for using the lib and let me know any further issues
