### ISSUE TITLE
onPageClickListener not working

### ISSUE THREAD

**Issue by ChiangChu** [voghDev/PdfViewPager#140]
Hi There,

currently I have a problem regarding your library. The OnPageClickListener is not working.
After looking into your code I know now why not,  because your saving it to a variable but after that your not doing anything with it. Shouldn't it be connected in the instantiateItem mode to the container click listener?

Because like that this method is useless.

Best Regards

**Comment by voghDev** [comment]
Hi!

thanks for reporting it. Can you link the exact lines with the method you've detected? I'm not sure if I understood you the right way :) Do you mean the ImageView inside the Adapter class? or the VIewPager itself?

Please link the file and I'll have a look 👍

**Comment by ChiangChu** [comment]
Hi,
Sure can do.
It is this class [PDFPagerAdapter](https://github.com/voghDev/PdfViewPager/blob/master/library/src/main/java/es/voghdev/pdfviewpager/library/adapter/PDFPagerAdapter.java). 

Best Regards.
