### ISSUE TITLE
why not add Vertically scroll pageview

### ISSUE THREAD

**Issue by zj2050** [voghDev/PdfViewPager#141]
if can add Vertically scroll pageview in new version ,it will be best

**Comment by voghDev** [comment]
Hi!

There's an experimental branch where you can scroll vertically. Have a look at issues like #81 or #46. I'll release an updated version of `1.1.0` that incorporates this vertical scrolling feature, but it's not ready yet.

Hope these issues can solve your needs :)

**Comment by zj2050** [comment]
> Hi!
> 
> There's an experimental branch where you can scroll vertically. Have a look at issues like #81 or #46. I'll release an updated version of `1.1.0` that incorporates this vertical scrolling feature, but it's not ready yet.
> 
> Hope these issues can solve your needs :)

thanks and looking forward

**Comment by codefury** [comment]
Hi Olmo,

Is there any update on Vertical View Pager for the RemotePDFViewPager? Any official release?

**Comment by voghDev** [comment]
Hi,

there is an updated version of the `vertical_viewpager` branch

You can try it using

`implementation 'es.voghdev.pdfviewpager:library:1.1.3'`

Let me know if it's useful for you

**Comment by abhinavtestbook** [comment]
hey , is there any extra parameter that we need to pass to enable vertical scrolling ? after updating library version to 1.1.3 its working for horizontal scroll only

**Comment by voghDev** [comment]
> hey , is there any extra parameter that we need to pass to enable vertical scrolling ? after updating library version to 1.1.3 its working for horizontal scroll only.
> P.S. currently passing file.absolutePath in PdfViewPager

Hi, it is a different View. Use a `VerticalPdfViewPager` instead of your `PdfViewPager`. You can see the code in the `vertical_viewpager` branch as mentioned above

**Comment by jamilxt** [comment]
@voghDev What about RemotePDFViewPager ? :( I'm using RemotePDFViewPager, and want that to be vertically scrolled.
