### ISSUE TITLE
 Some inquiries about lib support

### ISSUE THREAD

**Issue by azrael8576** [voghDev/PdfViewPager#143]
Does this lib limit the pdf version?
Does this lib limit the Mobile device?

**Comment by voghDev** [comment]
Hi,

what do you mean with pdf version? probably not, as the library doesn't do any check related to the pdf file, it just tries to open it, and handles the exceptions that could happen
And about the mobile device, definitely not. You can read the code and see there are no checks about device manufacturer or model :)

Hope this solves your question!
