### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by EmiyaAr** [voghDev/PdfViewPager#156]

**Comment by mayurr1512** [comment]
Add network security config file in xml resource directory- 
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">abc.co.in</domain>
    </domain-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>

**Comment by voghDev** [comment]
Are you trying to download a file under `https` with the default Downloader class?
You probably need to implement your own. Have a look at #157, where custom downloaders are mentioned
