### ISSUE TITLE
How to cancel the background download of Remotepdf

### ISSUE THREAD

**Issue by chetanmauth** [voghDev/PdfViewPager#157]
I have large files in remote, is there any option to cancel the background download while downloading through remotepdfviewpager.

**Comment by voghDev** [comment]
Hi,

for the moment it is not possible to cancel Pdf download but you can implement your own downloader and add it a `cancel()` method that you can call to cancel your current download.

All you have to do is pass your custom DownloadFile implementation to RemotePdfViewPager through this constructor

```
public RemotePDFViewPager(Context context,
                              DownloadFile downloadFile,
                              String pdfUrl,
                              DownloadFile.Listener listener) {
    ...
}
```

example

```
remotePdfViewPager = new RemotePDFViewPager(this, MyCustomDownloadFileImpl(), "http://path.to.my.pdf.file", downloadFileListener);
```

you can paste `DownloadFileUrlConnectionImpl` as an example and add your `cancel()` method

**Comment by chetanmauth** [comment]
thank you...
