### ISSUE TITLE
Height of all pages are the same size as the first one

### ISSUE THREAD

**Issue by tajoumal** [voghDev/PdfViewPager#16]
Hi,

In versions 0.3.0 and 1.0.1, if a PDF has multiple pages, and the pages are not the same height, there are display problems.

For example, if the first page is 500dp high, and the second one is 700dp high, the second page will appear compressed to fit in 500dp. I have also noticed severe lags in opening and flipping between pages.

This issue does not occur in 0.2.1.

I believe it might have something to do with the extractPdfParamsFromFirstPage method in BasePDFPagerAdapter.

Do you have an idea?

Tested on LG G4 / Android 5.1

Cheers

**Comment by voghDev** [comment]
`extractPdfParamsFromFirstPage`  gets the width and height of the first page, and applies this size to every page. This is faster for PDFs with the same page width/height, but may not work for your case.

I suggest you to subclass PdfPagerAdapter, and manage page width and height in a different way. You can copy the code from 0.2.1, or any old version that does not use `extractPdfParamsFromFirstPage`.

I'll review it later to see if there's a faster solution

**Comment by tajoumal** [comment]
Ok thanks, it worked, a bit laggy though, probably because the PDF is high res.

Cheers

**Comment by voghDev** [comment]
Probably. In next versions i'm planning to do the PDF rendering operations in a different thread to make UI performance smoother. I need to find a way to implement it without complicating library code too much
