### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by arkanoid17** [voghDev/PdfViewPager#161]
Is there a dark mode available if so, how to use it?
If not please can we get one.

**Comment by voghDev** [comment]
Hi @arkanoid17 !

sorry but dark mode is not supported at the moment. I can't figure how a "Dark mode" implementation of PdfViewPager would look, but in this moment, implementing one is not one of the priorities for this library.

Of course, all ideas are welcome about how dark mode can be supported in the library :-)

Hope this helps and sorry for the negative response

**Comment by voghDev** [comment]
Closing this for the moment. Someday the sky could become dark, we never know :-)
