### ISSUE TITLE
Susan

### ISSUE THREAD

**Issue by ice5771** [voghDev/PdfViewPager#165]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S6]
 - OS: [e.g. Android 8.1.1]

**Additional context**

**Comment by voghDev** [comment]
Hi,

could you provide more details about the issue? I see that the template is unmodified :smile:

**Comment by voghDev** [comment]
Closing Susan due to inactivity :-)
