### ISSUE TITLE
in reference of verticalViewPager

### ISSUE THREAD

**Issue by abhinavtestbook** [voghDev/PdfViewPager#167]
As discussed in #141 , the function accepts atributesSets as parameter but i need to pass pdf location path in sd card [file.absolutePath] , how to achieve it ?

**Comment by voghDev** [comment]
If you want to create the PdfViewPager by code, you can pass the absolute path directly. See [this code](https://github.com/voghDev/PdfViewPager/blob/vertical_viewpager/library/src/main/java/es/voghdev/pdfviewpager/library/PDFViewPager.java), you have a constructor for that.

If you need to pass it in your XML file, then you need to create your own subclass, as absolute paths are not supported via AttributeSet in XML layouts.

**Comment by abhinavtestbook** [comment]
actually I want to swipe it vertically and open it using pdf path [file.absolutePath]
