### ISSUE TITLE
Caching files response

### ISSUE THREAD

**Issue by AzharZouhir** [voghDev/PdfViewPager#168]
Can you add method to check whatever the file already being moved to cache directory

**Comment by voghDev** [comment]
Hi!

I'm afraid this is not supported. It can be easily implemented handling the download manually. Have a look at #157 or #138 to see how a custom downloader can be implemented. In this custom downloader you create, you can check the file presence in your cache directory before downloading. If you don't know how to proceed, just copy `DownloadFileUrlConnectionImpl` as your downloader, then modify it
