### ISSUE TITLE
New Feature: Scrolling vertically

### ISSUE THREAD

**Issue by jamilxt** [voghDev/PdfViewPager#169]
Hi, is that feature available on this library? if not, do you've plan for it. Seems like you've used ViewPager. I think migrating to ViewPager2 will help you to achieve it. Such a nice library it is! 

Thank you.

**Comment by voghDev** [comment]
Not a new feature actually :smile: it was implemented years ago, see #141 #166 #162 and many others :-)

Closing this if you don't mind, as it's duplicated

**Comment by jamilxt** [comment]
I need to download it offline as library, right?

**Comment by voghDev** [comment]
You mean the Pdf document?

yes, you need to store it somewhere in your sd card, then load it

**Comment by jamilxt** [comment]
> You mean the Pdf document?
> 
> yes, you need to store it somewhere in your sd card, then load it

no, I mean the other branch's library.

**Comment by voghDev** [comment]
Oh, sorry :-)

there is a separate release that was taken from this branch. it is `1.1.3` You can get the dependency from #141 :D

**Comment by arifaizin** [comment]
how about with RemotePDFViewPager?  I have use 1.1.3 and change to VerticalViewPager, but it still same.
