### ISSUE TITLE
Can you set it to slide left and right

### ISSUE THREAD

**Issue by zou1755815609** [voghDev/PdfViewPager#177]
Can you set it to slide left and right

**Comment by voghDev** [comment]
Yes, of course you can. Swiping left and right is the default behaviour :+1:

**Comment by gumuruhsspj** [comment]
what if slide it bottom to top and 
vice versa top to bottom...? in which syntax should we declare to achieve this functionality?

**Comment by voghDev** [comment]
> what if slide it bottom to top and vice versa top to bottom...? in which syntax should we declare to achieve this functionality?

#7 and the related issues.
