### ISSUE TITLE
Exception java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by ncurilovic** [voghDev/PdfViewPager#19]
I'm loading PDF from URL and sometimes when I scroll file it's fine sometimes it's crashing. I tested this on several phones and it's the same. Here is the log:

`android.view.MotionEvent.nativeGetAxisValue (MotionEvent.java)
android.view.MotionEvent.getX (MotionEvent.java:1983)
android.support.v4.view.MotionEventCompatEclair.getX (MotionEventCompatEclair.java:32)
android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX (MotionEventCompat.java:116)
android.support.v4.view.MotionEventCompat.getX (MotionEventCompat.java:496)
android.support.v4.view.ViewPager.onInterceptTouchEvent (ViewPager.java:2056)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2201)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2583)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2315)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2583)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2315)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2583)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2315)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2583)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2315)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2583)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2315)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2583)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2315)
com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent (PhoneWindow.java:2502)
com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1729)
android.app.Activity.dispatchTouchEvent (Activity.java:2786)
android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:60)
com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent (PhoneWindow.java:2463)
android.view.View.dispatchPointerEvent (View.java:8671)
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:4096)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:3959)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3521)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3574)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3540)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:3650)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3548)
android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:3707)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3521)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3574)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3540)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3548)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3521)
android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:5793)
android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:5767)
android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:5738)
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:5883)
android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:185)
android.view.InputEventReceiver.nativeConsumeBatchedInputEvents (InputEventReceiver.java)
android.view.InputEventReceiver.consumeBatchedInputEvents (InputEventReceiver.java:176)
android.view.ViewRootImpl.doConsumeBatchedInput (ViewRootImpl.java:5854)
android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run (ViewRootImpl.java:5906)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:767)
android.view.Choreographer.doCallbacks (Choreographer.java:580)
android.view.Choreographer.doFrame (Choreographer.java:548)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:753)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5536)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1397)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1192)`

**Comment by ncurilovic** [comment]
I created my own RemotePDFViewPager class and add following code to fix this issue:

`@Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            return super.onInterceptTouchEvent(ev);
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
            return false;
        }
    }`

**Comment by RichardPro** [comment]
often crash by this  when zoom in / out

**Comment by voghDev** [comment]
This issue is the same as #14. It is a bug in photoview library, can be fixed handling the exception
