### ISSUE TITLE
Low Quality

### ISSUE THREAD

**Issue by senhor** [voghDev/PdfViewPager#23]
Rendered PDF's has really bad quality especially when text is colored.

**Comment by voghDev** [comment]
Can you attach an screenshot or image to see what you mean?

I guess this is related to Android's `PdfRenderer` class itself.

**Comment by senhor** [comment]
This is the expected quality:

![screenshot_2016-11-13-20-58-38](https://cloud.githubusercontent.com/assets/5410942/20247719/61495a5a-a9dc-11e6-9d78-99b60e8715d9.png)

and this is what I get:

![screenshot_2016-11-13-21-01-48](https://cloud.githubusercontent.com/assets/5410942/20247720/6e89e7a2-a9dc-11e6-8c1f-8e40f26fba32.png)

I believe the problem is not with Android's `PdfRenderer` class itself. Your way of rendering is not proper. You should get a detailed render when the file is zoomed. You are just showing image files. I hope you can find a better way.

Thanks for your help and work.

**Comment by voghDev** [comment]
I see what you mean. Probably the initial rendered image loses quality when it is zoomed. As a quick workaround, I suggest you to subclass `PDFPagerAdapter` class and override `instantiateItem` and/or `init` to render a certain area of the PDF with better quality.

**Comment by senhor** [comment]
I have added a code like this but it doesn't work because the listener is called continuosly when you are pinching and it causes IllegalS:tateException: Current page is not closed. It looks there is not a simple way of achieving this. Anyway to support lower API's you can use `PDFium` instead android `PDFRenderer`

```
attacher.setOnScaleChangeListener(new PhotoViewAttacher.OnScaleChangeListener() {
            @Override
            public void onScaleChange(float scaleFactor, float focusX, float focusY) {
                PdfRenderer.Page page = getPDFPage(renderer, position);

                Matrix m = new Matrix();

                attacher.getDisplayMatrix(m);

                RectF rectF = attacher.getDisplayRect();

                Bitmap bitmap = bitmapContainer.get(position);
                page.render(bitmap, new Rect((int)rectF.left, (int)rectF.top, (int)rectF.right, (int)rectF.top), m, PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);
                page.close();

                iv.setImageBitmap(bitmap);
            }
        });
```

**Comment by dchp** [comment]
Thin gray letters are unreadable.
![text](https://user-images.githubusercontent.com/29485880/27231933-998f0e74-52b4-11e7-9f4e-d0c00549b3f6.png)
(source: LG Nexus 5X; max zoom)

**Comment by lampofdrog** [comment]
I have the same issues, i use pdfrendrer and i apply this rule 

-------------------------------------------------

Bitmap bitmap = Bitmap.createBitmap(getResources().getDisplayMetrics().densityDpi/ 72 * currentPage.getWidth(),
                getResources().getDisplayMetrics().densityDpi/ 72 * currentPage.getHeight() ,
                Bitmap.Config.ARGB_8888);

![screenshot_2018-03-16-15-51-30](https://user-images.githubusercontent.com/11801709/37530667-015713e0-2932-11e8-8598-a14d59e87ea3.png)
