### ISSUE TITLE
Could not find class 'android.graphics.pdf.PdfRenderer'

### ISSUE THREAD

**Issue by rastha67** [voghDev/PdfViewPager#27]
it works fine with marshmallow and lollipop but crashes below it showing error below:
![screenshot from 2016-11-23 07-58-02](https://cloud.githubusercontent.com/assets/12842154/20549353/86ef7590-b153-11e6-9903-c0b1cd2493ef.png)

**Comment by voghDev** [comment]
Yup, refer to #26 and #9

**Comment by voghDev** [comment]
I guess you've found the cause of the problem and the way to solve it in the referred issues. Gonna close this, let me know any other issues you have.
