### ISSUE TITLE
Problem merging library's Manifest: "android:allowBackup"

### ISSUE THREAD

**Issue by anas-ambri** [voghDev/PdfViewPager#28]
In my app, I need "android:allowBackup" to be false, but it seems that it has been set to true in the library's AndroidManifest. 
This is similar to the issue reported here: https://github.com/voghDev/PdfViewPager/issues/11

While there is a workaround for this, it might be worthwhile to make the change to remove it as well. It is set to true by default, which is probably why it shows up in the generated AndroidManifest, even though you have not *explicitly* set it as such.

I would be happy to provide with a PR if that works for you.

Thanks for the library, btw! Extremely useful and handy!

**Comment by voghDev** [comment]
Ok, I'll have a look at this attribute in the samples and the library project. 

Thanks for reporting

**Comment by voghDev** [comment]
In the meanwhile, have you tried to ignore `android:allowBackup` the same way `android:icon` is ignored in #11? Never tried something similar tbh

**Comment by anas-ambri** [comment]
Yeah, that's basically the workaround I mentioned. It's not critical, just annoying :)

**Comment by andreashermann** [comment]
@voghDev: Did you plan to create a release that includes this fix?
I'm eager to update to avoid those merge rules.
Thanks for your awesome lib!

**Comment by voghDev** [comment]
Hi Andreas,
I thought it was released already. I'll have a look and release it together with another changes.

Thanks!

**Comment by voghDev** [comment]
Hi again, I've released `1.0.2` that fixes these manifest conflicts. If you want to have a look at the code it is located in the [vertical_viewpager branch](https://github.com/voghDev/PdfViewPager/tree/vertical_viewpager). There is a full list of changes in [CHANGELOG.md](https://github.com/voghDev/PdfViewPager/blob/vertical_viewpager/CHANGELOG.md)

Let me know if this solves manifest conflicts

**Comment by andreashermann** [comment]
The Manifest changes work as expected. 
Thank you very much for taking the time to create a new release!

**Comment by voghDev** [comment]
You're welcome mate :) I'm glad they do

**Comment by janvde** [comment]
Can you please update the README to this version 1.0.2? I had the same problem, because I installed the 1.0.1 version and had to to search for this issue to find out it has already been resolved.

**Comment by anas-ambri** [comment]
@janvde I mean, the README clearly states that latest is 1.0.2...

**Comment by janvde** [comment]
It doesn't under the 'installation' header.

**Comment by voghDev** [comment]
Well `1.0.2` was quite of an experimental branch, I'm not sure if making it the official one. If this version helped you fixing an issue, then it would be ok to add it in the README, I guess.

Thanks for the feedback

**Comment by voghDev** [comment]
Uploaded a version `1.0.3` that is similar to `1.0.2` but without the experimental features (vertical ViewPager). This issue should not give more headaches :-)

**Comment by voghDev** [comment]
Hi,

there is an updated version of the `vertical_viewpager` branch

You can try it using

`implementation 'es.voghdev.pdfviewpager:library:1.1.3'`

Let me know if it's useful for you
