### ISSUE TITLE
PDFViewPager not showing highlighted text in the PDF

### ISSUE THREAD

**Issue by sumithub** [voghDev/PdfViewPager#29]
Hi Vogh,

I'm working on an application that requires highlighting text in a PDF and then open it using PDFViewPager. When I open it through PDFViewPager it does not show the highlighted text but otherwise opening via chrome shows highlighted text. 

Just wondering what could be the cause of this issue? I'm attaching the sample PDF that highlights "basic" keyword 7 times in the document but not showing up using PDFViewPager. Pls help.
[chemical_classification_periodicity_in_properties (7).pdf](https://github.com/voghDev/PdfViewPager/files/628636/chemical_classification_periodicity_in_properties.7.pdf)

**Comment by voghDev** [comment]
Hi,

I can't see the highlighted words you mention. Is the text highlighting part of the PDF itself? In this case, `PdfRenderer` class should display it. Honestly I haven't used PdfViewPager with highlighted PDFs.

**Comment by sumithub** [comment]
Thanks voghDev. Would appreciate if you provide some example code to use PDFRenderer to display a PDF file.
 Thanks

**Comment by voghDev** [comment]
Oh, maybe I wasn't clear enough :) the `PdfRenderer` class is the one that `PdfViewPager` uses to render documents.

You can see more info [in the official documentation](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer.html) as well as sample code in the [PdfRendererBasic sample](https://github.com/googlesamples/android-PdfRendererBasic)

I'm afraid your issue with the highlighting will appear also in the sample projects, you can give it a try though.
