### ISSUE TITLE
PDFs are displayed only 1/2 the screen size by default

### ISSUE THREAD

**Issue by carstenbaumhoegger** [voghDev/PdfViewPager#3]
Hey Olmo,
I really like this lib! :)
I played a bit with it but PDFs are displayed quite small on my test-devices. 
I had to call `pdfViewPager.setScaleX(2)` to make them appear fullscreen.
Is this an intended behaviour?

Best regards
Carsten

**Comment by voghDev** [comment]
Hello!
with "quite small" you mean not zoomed? each PDF page is rendered just as PDFRenderer returns it. If you want the user to zoom in and out with pinch gestures, PDFViewPagerZoom may suit your needs (available in versions 0.2.0 and above).
Setting a specific zoom level is not supported at the moment, could be a good idea for future versions.

**Comment by carstenbaumhoegger** [comment]
Yeah right, the page is not zoomed.
I already use PDFViewPagerZoom but I don't think that the user want's to zoom into the page so that it appears fullscreen.
I'd really like to see a functionality like this so that I can force the PDF to fill the screen space.

Keep up the great work!
Carsten

**Comment by voghDev** [comment]
Hi again,
I'm implementing a first approach in the make_scale_setable branch. Hopefully when 0.2.2 is released, this feature will be included. The code is available here:

https://github.com/voghDev/PdfViewPager/tree/make_scale_setable/library/src/main/java/es/voghdev/pdfviewpager/library

**Comment by voghDev** [comment]
Hi again

version 1.0.0 is about to be released with a setScale-capable adapter. You can set a scale level and it will set it to each page. Let me know if it suits your needs.

**Comment by voghDev** [comment]
Hi,

Version *1.0.0* released. You can now set a default scale to the PDFPagerAdapter, so every rendered page will have this scale applied.

There is a sample included in samples project, have a look at it and let me know if it suits your needs.
