### ISSUE TITLE
Android 6.0 cannot be resolved

### ISSUE THREAD

**Issue by GstXu** [voghDev/PdfViewPager#30]
![image](https://cloud.githubusercontent.com/assets/21048699/21042861/1c91f022-be2f-11e6-9738-84d629cdf7c1.png)

**Comment by GstXu** [comment]
Great god rescue

**Comment by voghDev** [comment]
What's the error you have? Is it an exception? or is it the PDF not displaying properly?

**Comment by GstXu** [comment]
It is in the Genymotion5.0 can display properly,the in 6.0 bug situation will occur!

**Comment by voghDev** [comment]
Can you upload the PDF where this is happening so I can test it in my devices?

**Comment by voghDev** [comment]
Well, I close this for the moment. If you have the non-working PDF available, send it to me or open a new issue :)
