### ISSUE TITLE
Provide vertical View pager within the library using ViewPager from support library

### ISSUE THREAD

**Issue by anas-ambri** [voghDev/PdfViewPager#31]
First, thank you for taking the time to create this library.

I ran into this other project: https://github.com/castorflex/VerticalViewPager, which provides with a VerticalViewPager without RecyclerView, and I was wondering if:
- This would be feasible (I know that combining Recyclerview & PdfRenderer has limitations for large files).
- How easy it would be to combine with your library.

If you think it is possible, I would happy to provide with a PR.

**Comment by voghDev** [comment]
Hello! Thanks for the issue

some months ago I started [this RecyclerView + PdfRenderer experiment](https://github.com/voghDev/PdfRecyclerView) and temporary discarded it, mainly for memory limitations as you well said. 

Never knew about this approach to Vertical View Pager, swapping X and Y axis. I'll open a branch and do some research :) Thanks!

**Comment by anas-ambri** [comment]
Cool. Please keep me posted on this. Cheers!

**Comment by voghDev** [comment]
Commited the first `VerticalViewPager` to the branch, adapted from [castorflex's implementation](https://github.com/castorflex/VerticalViewPager). it is not `PDF` yet 

you can have a look at the code [here](https://github.com/voghDev/PdfViewPager/tree/vertical_viewpager) if you want.

**Comment by voghDev** [comment]
Hi again, I've released version `1.0.2` that includes the first implementation of the `VerticalViewPager`.

code is commited in the [vertical_viewpager branch](https://github.com/voghDev/PdfViewPager/tree/vertical_viewpager)

Gradle dependency should be available for download in a few minutes

    compile 'es.voghdev.pdfviewpager:library:1.0.2'

All changes have been included in [CHANGELOG.md](https://github.com/voghDev/PdfViewPager/blob/vertical_viewpager/CHANGELOG.md)

**Comment by voghDev** [comment]
Hi,

there is an updated version of the `vertical_viewpager` branch

You can try it using

`implementation 'es.voghdev.pdfviewpager:library:1.1.3'`

Let me know if it's useful for you
