### ISSUE TITLE
Crash when rendering some pdfs.

### ISSUE THREAD

**Issue by Rflyee** [voghDev/PdfViewPager#33]
I downloaded the pdf from [https://tools.ietf.org/pdf/rfc7519.pdf](url) . Then replace adobe.pdf with rfc7519.pdf.  It is very slow when rendering rfc7519.pdf. And crashed after a while. I found the culprit：
`return renderer.openPage(position);`
But other pdfs is fine, witch is evan larger than rfc7519.pdf.
You can reproduce it with the rfc7519.pdf.

**Comment by Rflyee** [comment]
This one is the same.
https://github.com/barteksc/AndroidPdfViewer/files/329537/pdfSample.pdf

**Comment by Rflyee** [comment]
This one is the same. [pdfSample.pdf](https://github.com/barteksc/AndroidPdfViewer/files/329537/pdfSample.pdf)

**Comment by josearmandoam** [comment]
Hello,

I've reproduced the issue in my phone, with your PDF. It also crashes in my phone. We will have a look to see if we can fix the issue in any way.

**Comment by josearmandoam** [comment]
I found a similar issue about this, https://github.com/googlesamples/android-PdfRendererBasic/issues/1
Are you reading your pdf files directly from assets.
I suggest you to copy the files in your own SD card

**Comment by Rflyee** [comment]
No difference，from assets or SD card , all crash. But i found it not crash in some phones. I count not find the cause. When it crash , here is the log :
`es.voghdev.pdfviewpager A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 16545 (ev.pdfviewpager)` 
it look like it is missing '.so' libs.

**Comment by voghDev** [comment]
Hello,

it looks like an internal error of `PdfRenderer` class. If the original PdfRenderer can't render your PDF file, I guess this library can't do anything about it, as it is mounted on top of it, sorry about that :-/

I suggest you to stay tuned on the issue that @josearmandoam linked, and let me know if they find a solution. I'll update the library with any changes that may be necessary
