### ISSUE TITLE
change max zoom level

### ISSUE THREAD

**Issue by registrochin** [voghDev/PdfViewPager#34]
Hi.

I have an application wich it has large-width pdf files and very small text size (provided by the WS). So I need to be capable of doing a great maximum zoom, more the default 3x in the PhotoViewAttacher class.

¿Could you add in the future this feature, for example in the PDFPagerAdapter builder class?

Thanks a lot!

**Comment by voghDev** [comment]
Hi,

haven't done a deep research yet, but setMaxZoomLevel sounds like an implementation detail of the PhotoView library. I'll have a look at the code and think about including it min/max zoom level, maybe in an experimental branch like 1.0.1 :)

Thanks for using the lib!

**Comment by devrtk** [comment]
did you include yet? bro

**Comment by voghDev** [comment]
Closing this to inactivity. Hope you finally wrote your own Adapter class with the `setMaxZoomLevel` method that you desired ;-)
