### ISSUE TITLE
Make a phone call after clicking on phone number

### ISSUE THREAD

**Issue by snchitnis** [voghDev/PdfViewPager#36]
Hi Olmo, 

How can I trigger a intent to make a phone call, after clicking on specific number in pdf OR open a mail client after clicking on email id from pdf ? Not sure whether it is possible or not.

**Comment by josearmandoam** [comment]
I have tested this case and links inside PDF Document are not clickable, I mean they do not redirect you to the website

**Comment by voghDev** [comment]
Hi,

you can set a click listener on the whole PdfViewPager, but I'm afraid the links won't be clickable. See #12 for more info about the listener.

Hope this helps you in any way. Thanks for using the library
