### ISSUE TITLE
Unable to integrate this library in my app

### ISSUE THREAD

**Issue by ervinod** [voghDev/PdfViewPager#37]
I m unable to add this library in my project. Please help..... Can u explain easy way to integrate this library in my project......

**Comment by ervinod** [comment]
please help me.....

**Comment by voghDev** [comment]
Hello,

you can integrate the lib as a gradle dependency

    compile 'es.voghdev.pdfviewpager:library:1.0.1'

Or directly download the code and copy it into a folder named `PdfViewPager` inside your project folder, then in your `settings.gradle` fie: 

    include ':app', ':PdfViewPager'

After reading #39, did you finally manage to configure it? Can I consider this issue closed then?

**Comment by ervinod** [comment]
Thanks I done it.....

**Comment by voghDev** [comment]
;) you're welcome
