### ISSUE TITLE
Two pages when in landscape mode

### ISSUE THREAD

**Issue by Delsons** [voghDev/PdfViewPager#38]
Is it possible to have two pages in screen when the device is in landscape mode?

**Comment by voghDev** [comment]
Hello,

sounds interesting. I guess this is not supported by `ViewPager` by default (`PdfViewPager` is just a subclass of `ViewPager`), so it looks like it can't be done directly.

What I would do if I had to implement this, is to create a Custom View with two `PdfRenderer` objects in landscape mode, and render one page on each.

**Comment by Delsons** [comment]
Thank you for the Tip! I will try and return with feedback 

Best Regards
Delson 

Enviado do meu iPhone

**Comment by voghDev** [comment]
;) you're welcome mate. Let me know any progress
