### ISSUE TITLE
Pdf not displaying correctly .......

### ISSUE THREAD

**Issue by ervinod** [voghDev/PdfViewPager#39]
When i open pdf on button click it is not displayed in first attempt, blank activity is showing when i click on button.... need to go back and need to click again on button then pdf is displayed ...... please anyone have solution.....

Here are contents of my  **MainActivity.java**

package com.beqpapers.activities;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import com.beqpapers.R;

public class MainActivity extends AppCompatActivity {
    Button b1;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

    }
    public void btnOpen(View view){
        Intent i = new Intent(MainActivity.this, SecondActivity.class);
        startActivity(i);
    }
    
}

**SecondActivity.java**

package com.beqpapers.activities;

import android.os.Handler;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.beqpapers.R;

import java.io.File;

import es.voghdev.pdfviewpager.library.asset.CopyAsset;
import es.voghdev.pdfviewpager.library.asset.CopyAssetThreadImpl;

public class SecondActivity extends AppCompatActivity {
    final String[] sampleAssets = {"DWM_May_2016.pdf"};
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_second);

        initSampleAssets();
    }

    private void initSampleAssets() {
        CopyAsset copyAsset = new CopyAssetThreadImpl(this, new Handler());
        for (String asset : sampleAssets) {
            copyAsset.copy(asset, new File(getCacheDir(), asset).getAbsolutePath());
        }
    }
}

**activity_second.xml**

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.beqpapers.activities.SecondActivity">

    <es.voghdev.pdfviewpager.library.PDFViewPager
        android:id="@+id/pdfViewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:assetFileName="DWM_May_2016.pdf"/>

</RelativeLayout>

Please help me to resolve this issue.......

**Comment by voghDev** [comment]
It seems that you are copying the PDF file and opening it at the same time. Try to copy it before opening it (for example in `MainActivity`, or `Application` class), then make sure the `File` exists before opening in `SecondActivity`

**Comment by ervinod** [comment]
Thank you very much for your valuable feedback..... I solved this issue now.
Is there is any way to add scrollbar to pdf having more than one pages.......

**Comment by voghDev** [comment]
Your question looks similar to #38. As I said there, `ViewPager` only supports one as far as I know. Gonna close this then. Hope you enjoy the lib!
