### ISSUE TITLE
zoom level below 1f

### ISSUE THREAD

**Issue by ptdede** [voghDev/PdfViewPager#41]
Hi, 
is it possible to set zoom level below 1f? 

```
      adapter = new PDFPagerAdapter.Builder(this)
                                     .setScale(.6f)
                                     .setPdfPath(FileUtil.extractFileNameFromURL(url))
                                     .create();

        remotePDFViewPager.setAdapter(adapter);
        pdf_container.addView(remotePDFViewPager);
```

**Comment by voghDev** [comment]
Hmm I haven't tried this case.
Did you finally manage to solve it?

If not, We'll give it a try and tell you the result

**Comment by voghDev** [comment]
Just FYI, I've release this adapter that allows a better zoom in and out capability. Brought me good quality in every app I tried.

https://gist.github.com/voghDev/8942ae2eb0904aa2572180fa1f74546b

You might want to have a look, It's written in Kotlin
