### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by diogorjs** [voghDev/PdfViewPager#42]
Hello, I'm trying to install PdfViewPager but I'm getting an error as below

```
Attribute application@label value=(@string/comp_app_name) from AndroidManifest.xml:18:9-50
	is also present at [es.voghdev.pdfviewpager:library:1.0.1] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:14:5-99:19 to override.
```

Problem is that I 'laready have tools:replace="icon, theme" in my Manifest. I already tried valious combinations but none of them works. Could you please advice?

Thanks

**Comment by voghDev** [comment]
Which version are you importing? 1.0.0 or 1.0.1?

**Comment by diogorjs** [comment]
Hello, I'm using 1.0.1

I have only one manifest and it is as below (already with tools:replace):

 <application
        android:name=".Application"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/BlueTheme"
        tools:replace="icon, theme">
        <activity
...

Thanks

**Comment by voghDev** [comment]
Hmm
The library is imported in [this project for example](https://github.com/voghDev/HelloKotlin/blob/pdfviewpager/app/build.gradle). If your manifest is similar to this one and there are no clases with other libs, it should be fine.

**Comment by voghDev** [comment]
Another thing you can try is to import `1.0.2`. Some users had their issues with previous versions solved with this one.
