### ISSUE TITLE
Scroll Vertically

### ISSUE THREAD

**Issue by brandlee** [voghDev/PdfViewPager#46]
thanks to your library, I want to ask if this library can support scroll vertically?

**Comment by voghDev** [comment]
Release 1.0.2 includes code from an experimental branch called `vertical_viewpager`. You can use an unofficial widget called  `VerticalPDFViewPager` that is included on it.

[example code](https://github.com/voghDev/PdfViewPager/blob/vertical_viewpager/sample/src/main/res/layout/activity_vertical_pdf_view_pager.xml)

**Comment by Jeraldy** [comment]
How do I use VerticalPDFViewPager with RemotePDFViewPager Or How do I load from remote urls in VerticalPDFViewPager . Can't find a way to integrate it. 
Thanks

**Comment by TomTasche** [comment]
I found a way to enable vertical scrolling. Just copy this class into your project and use the newly created class in your layout.xml instead of the class provided by this library:

```
import android.content.Context;
import android.util.AttributeSet;
import android.view.MotionEvent;
import android.view.View;

import androidx.viewpager.widget.ViewPager;
import es.voghdev.pdfviewpager.library.PDFViewPager;

// taken from: https://android.googlesource.com/platform/packages/apps/DeskClock/+/master/src/com/android/deskclock/VerticalViewPager.java
public class VerticalViewPager extends PDFViewPager {

    public VerticalViewPager(Context context) {
        this(context, null);
    }
    public VerticalViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
        init();
    }

    /**
     * @return {@code false} since a vertical view pager can never be scrolled horizontally
     */
    @Override
    public boolean canScrollHorizontally(int direction) {
        return false;
    }
    /**
     * @return {@code true} iff a normal view pager would support horizontal scrolling at this time
     */
    @Override
    public boolean canScrollVertically(int direction) {
        return super.canScrollHorizontally(direction);
    }
    private void init() {
        // Make page transit vertical
        setPageTransformer(true, new VerticalPageTransformer());
        // Get rid of the overscroll drawing that happens on the left and right (the ripple)
        setOverScrollMode(View.OVER_SCROLL_NEVER);
    }
    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        final boolean toIntercept = super.onInterceptTouchEvent(flipXY(ev));
        // Return MotionEvent to normal
        flipXY(ev);
        return toIntercept;
    }
    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        final boolean toHandle = super.onTouchEvent(flipXY(ev));
        // Return MotionEvent to normal
        flipXY(ev);
        return toHandle;
    }
    private MotionEvent flipXY(MotionEvent ev) {
        final float width = getWidth();
        final float height = getHeight();
        final float x = (ev.getY() / height) * width;
        final float y = (ev.getX() / width) * height;
        ev.setLocation(x, y);
        return ev;
    }
    private static final class VerticalPageTransformer implements ViewPager.PageTransformer {
        @Override
        public void transformPage(View view, float position) {
            final int pageWidth = view.getWidth();
            final int pageHeight = view.getHeight();
            if (position < -1) {
                // This page is way off-screen to the left.
                view.setAlpha(0);
            } else if (position <= 1) {
                view.setAlpha(1);
                // Counteract the default slide transition
                view.setTranslationX(pageWidth * -position);
                // set Y position to swipe in from top
                float yPosition = position * pageHeight;
                view.setTranslationY(yPosition);
            } else {
                // This page is way off-screen to the right.
                view.setAlpha(0);
            }
        }
    }
}
```

**Comment by NikhilPereira** [comment]
> vertical scrolling. Just copy this class into your project and use the newly created class in your layout.xml instead of the class provided by this library

This is not working

**Comment by voghDev** [comment]
Hi,

there is an updated version of the `vertical_viewpager` branch

You can try it using

`implementation 'es.voghdev.pdfviewpager:library:1.1.3'`

Let me know if it's useful for you

**Comment by nikgupta1231** [comment]
Hi, can you officially publish the vertical_viewpager library?

**Comment by voghDev** [comment]
nope, that's an experimental branch that doesn't passes code style checks because it contains a very old version of the `ViewPager` class. I only keep it for those who need it, but it's not part of the official release

**Comment by nikgupta1231** [comment]
Okay, So is there any other way to use the library 'es.voghdev.pdfviewpager:library:1.1.2' and make the scroll vertical?

**Comment by voghDev** [comment]
A simple way to achieve that would be to get the code for the `VerticalViewPager` and the `VerticalPdfViewPager` and adapt it to your needs. It's available for you [here](https://github.com/voghDev/PdfViewPager/blob/vertical_viewpager/library/src/main/java/es/voghdev/pdfviewpager/library/util/VerticalViewPager.java)

**Comment by gumuruhsspj** [comment]
> A simple way to achieve that would be to get the code for the `VerticalViewPager` and the `VerticalPdfViewPager` and adapt it to your needs. It's available for you [here](https://github.com/voghDev/PdfViewPager/blob/vertical_viewpager/library/src/main/java/es/voghdev/pdfviewpager/library/util/VerticalViewPager.java)

probably if there's a small code snippet of the 'how to use' this viewscrollpager?
