### ISSUE TITLE
how to page count on page scroll

### ISSUE THREAD

**Issue by yashshekhada** [voghDev/PdfViewPager#47]
i need page count on page scroll event when i page scroll then display page position

**Comment by voghDev** [comment]
Hi,

maybe your issue is similar to #5 ? 

In case it is not, please explain your requirements in more depth

**Comment by SeanZom** [comment]
```java
int count = pdfViewPager.getAdapter().getCount();   // get page count

pdfViewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                setPageIndex(position + 1);
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });
```

**Comment by voghDev** [comment]
Thanks @SeanZom. I guess the setPageIndex method shows the counter with the current page value

**Comment by poorankharol** [comment]
pdfViewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                setPageIndex(position + 1);
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });

this code is not working can you please help
