### ISSUE TITLE
Page Counter

### ISSUE THREAD

**Issue by TheMatrix19** [voghDev/PdfViewPager#5]
HI All...
Please tell me how to add the functionally to jump to any page and count the total page and show the number of page..
And how to vertically swipe to go to next page

**Comment by voghDev** [comment]
Jump to any page

    pdfViewPager.setCurrentItem(3);
    pdfViewPager.setCurrentItem(3, true); // Can be used if you want to show a scroll animation

Get current page number

    pdfViewPager.getCurrentItem();

Get number of pages 

    pdfViewPager.getAdapter().getCount()

**Comment by TheMatrix19** [comment]
I want to scroll pages vertically insted of horizentaly..
And also tell me how to set custome minimum zoom level.

**Comment by voghDev** [comment]
Hi,

PdfViewPager inherits from Android's ViewPager, so vertical scrolling is not supported by this widget. If plenty of the lib users are interested in vertical scrolling, could be interesting to implement a PdfRecyclerView widget.
In order to set a minimum zoom level, it is still in development. You can use setScaleX in the meanwhile, like this:

    pdfViewPager.setScaleX( 1.5f )

**Comment by voghDev** [comment]
According to the vertical scrolling thing, there is [this open issue](https://github.com/voghDev/PdfViewPager/issues/7). We follow the discussion there to avoid duplicates please. I close this one

Thanks for using the lib! :)

**Comment by sunil-singh-chaudhary** [comment]
how to show currentpageno/Totalpages in pdf 
i know
 Get current page numbe
pdfViewPager.getCurrentItem();
Get number of pages
pdfViewPager.getAdapter().getCount()
but how to use it on PDF when open page

**Comment by voghDev** [comment]
Hi,

what do you mean? can you explain a bit more what you're trying to do?

**Comment by voghDev** [comment]
Hi,

there is an updated version of the `vertical_viewpager` branch

You can try it using

`implementation 'es.voghdev.pdfviewpager:library:1.1.3'`

Let me know if it's useful for you
