### ISSUE TITLE
download PDF don't have watermark

### ISSUE THREAD

**Issue by SuperBigJJJJJam** [voghDev/PdfViewPager#51]
![123](https://user-images.githubusercontent.com/12798912/30463118-8499cce0-99fc-11e7-834d-74da8e8ede92.png)

Hi, the left pdf is from iOS and web site,both of them can show the watermark.
while the right pdf is using PdfViewPager,as u see,don't have watermark.
can you give me some suggestions? Thank you very much

**Comment by voghDev** [comment]
I guess this issue is related to Google's `PdfRenderer` itself. For some reason, it is not displaying the watermark. This library does not control the details of the document rendering, just provides a wrapper to make its usage easier. Sorry :-/
