### ISSUE TITLE
Pdf Viewer can not read custom fonts.

### ISSUE THREAD

**Issue by khemrajsharma** [voghDev/PdfViewPager#54]
Hi this is a link which client want to read.it is opening in google viewer. but not in android pdfviewer that i used. I need this urgently.

https://igenbucket.s3.ap-south-1.amazonaws.com/1505737193910_1505737193728History-hin-1A.pdf

**Comment by bauer-bao** [comment]
I met the same problem. PdfRenderer.class is provided by google, so i tried the google sample to load the pdf. This issue still exists.

**Comment by voghDev** [comment]
Yes, I guess the issue is related to `PdfRenderer` class itself, because `PdfViewPager` does not treat the fonts or manipulate the file in any way
