### ISSUE TITLE
Page curl animation ?

### ISSUE THREAD

**Issue by umarF** [voghDev/PdfViewPager#59]
Hi,

Your library is perfect for use, however I need page curl animation on page turn, is it added ?
If not can you add or suggest me how to proceed with it ?

**Comment by voghDev** [comment]
Hi, 

Page curl animation is not added in the library. The widget is just a regular `ViewPager`, so I'm not sure if it's possible to implement curl animation on it. 

If you manage to implement it (after a simple search I found [these two answers](https://stackoverflow.com/questions/14930279/page-curl-with-view-pager), don't know how well they work), you can extend PdfViewPager class and override the methods you need, or create a complete new widget that supports curl animation and renders Pdf documents using a PdfRenderer, as PdfViewPager does. 

Good luck and happy 2018 :-)
