### ISSUE TITLE
Sometimes Can't read assets folder's pdf file

### ISSUE THREAD

**Issue by TheMatrix19** [voghDev/PdfViewPager#6]
i m using the same code for assets folder that are given in the pdfViewPager example.
This code sometimes read assets folder's pdf file but sometime it can not read the file and screen is shown blank and it gives error file is not available.
file from sd card always read and successfully show in app and when the sd card file shows than i change the code to show file through assets folder without taking sd card read permission and the file successfully shows..
will you please tell me the right way to read assets folder file.
i am using this code for copy assets sometime it successfully read the file but sometimes fail. 

final String[] sampleAssets = {"adobe.pdf","sample.pdf"};
 @Override
    public void onCreate() {
        super.onCreate();
        initSampleAssets();
    }
    private void initSampleAssets() {
        CopyAsset copyAsset = new CopyAssetThreadImpl(this, new Handler());
        for(String asset : sampleAssets){
            copyAsset.copy(asset, new File(getCacheDir(), asset).getAbsolutePath());
        }
    }

**Comment by voghDev** [comment]
Your code is fine. 
The exact code that performs the copy is this one:

    public static boolean copyAsset(Context ctx, String assetName, String destinationPath) throws IOException{
        InputStream in = ctx.getAssets().open(assetName);
        File f = new File(destinationPath);
        f.createNewFile();
        OutputStream out = new FileOutputStream(new File(destinationPath));

        byte[] buffer = new byte[1024];
        int read;
        while((read = in.read(buffer)) != -1){
            out.write(buffer, 0, read);
        }
        in.close();
        out.close();

        return true;
    }

You could call this function and copy the assets on SD card by yourself, without using a CopyAsset object. You can then log what getAssets() and open() are returning, and find the error.

It never happened to me. I'll do some tests to find if CopyAsset fails in some cases.

**Comment by voghDev** [comment]
Hi again,

have you finally managed to read the assets folder?

**Comment by narendra9593** [comment]
Code 
public class PDFViewPagerActiivty extends Activity {

    PDFViewPager pdfViewPager;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity);
        pdfViewPager = (PDFViewPager) findViewById(R.id.pdfViewPagerZoom);
    }
    @Override
    protected void onDestroy() {
        super.onDestroy();

        BasePDFPagerAdapter adapter = (BasePDFPagerAdapter) pdfViewPager.getAdapter();

        if(adapter != null) {
            adapter.close();
            adapter = null;
        }
    }

}

Layout --------------------
<es.voghdev.pdfviewpager.library.PDFViewPager
        android:id="@+id/pdfViewPagerZoom"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:assetFileName="adobe.pdf"
        />

ERROR
------------------

java.io.FileNotFoundException: No such file or directory
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at android.os.Parcel.openFileDescriptor(Native Method)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:270)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.getSeekableFileDescriptor(BasePDFPagerAdapter.java:98)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init(BasePDFPagerAdapter.java:62)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.<init>(BasePDFPagerAdapter.java:56)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.<init>(PDFPagerAdapter.java:37)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at es.voghdev.pdfviewpager.library.PDFViewPager.initAdapter(PDFViewPager.java:62)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at es.voghdev.pdfviewpager.library.PDFViewPager.init(PDFViewPager.java:57)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at es.voghdev.pdfviewpager.library.PDFViewPager.<init>(PDFViewPager.java:37)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
06-09 06:57:04.917 28201-28201/com.app.android.cync W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.transition.Scene.enter(Scene.java:175)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at com.android.internal.policy.PhoneWindow.transitionTo(PhoneWindow.java:451)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:391)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.app.Activity.setContentView(Activity.java:2166)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at com.app.android.cync.SplashActiivty.onCreate(SplashActiivty.java:24)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.app.Activity.performCreate(Activity.java:6237)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.os.Looper.loop(Looper.java:148)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-09 06:57:04.918 28201-28201/com.app.android.cync W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-09 06:57:04.922 28201-28240/com.app.android.cync D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
                                                                      
                                                                      [ 06-09 06:57:04.955 28201:28201 D/         ]
                                                                      HostConnection::get() New Host Connection established 0xab0f2da0, tid 28201
06-09 06:57:05.065 28201-28240/com.app.android.cync D/libEGL: loaded /system/lib/egl/libEGL_emulation.so
06-09 06:57:05.066 28201-28240/com.app.android.cync D/libEGL: loaded /system/lib/egl/libGLESv1_CM_emulation.so
06-09 06:57:05.070 28201-28240/com.app.android.cync D/libEGL: loaded /system/lib/egl/libGLESv2_emulation.so
                                                              
                                                              [ 06-09 06:57:05.079 28201:28240 D/         ]
                                                              HostConnection::get() New Host Connection established 0xab0f2e80, tid 28240
06-09 06:57:05.124 28201-28240/com.app.android.cync I/OpenGLRenderer: Initialized EGL, version 1.4
06-09 06:57:05.291 28201-28240/com.app.android.cync W/EGL_emulation: eglSurfaceAttrib not implemented
06-09 06:57:05.291 28201-28240/com.app.android.cync W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xab0ebcc0, error=EGL_SUCCESS
06-09 07:53:21.436 28201-28209/com.app.android.cync E/System: Uncaught exception thrown by finalizer
06-09 07:53:21.437 28201-28209/com.app.android.cync E/System: java.lang.NullPointerException: Attempt to invoke virtual method 'void dalvik.system.CloseGuard.warnIfOpen()' on a null object reference
                                                                  at android.graphics.pdf.PdfRenderer.finalize(PdfRenderer.java:210)
                                                                  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by voghDev** [comment]
@narendra9593: Maybe you are trying to open the file before the copy has completed? You can, for example, set the adapter to the PdfViewPager once the copy has been completed, or open the activity once the copy has been done.

**Comment by voghDev** [comment]
Example code of my last comment:

    CopyAsset copyAsset = new CopyAssetThreadImpl(getApplicationContext(), new Handler(), new CopyAsset.Listener() {
            @Override
            public void success(String assetName, String destinationPath) {
                pdfViewPager = new PDFViewPager(context, getPdfPathOnSDCard(Environment.getExternalStorageDirectory()));
                setContentView(pdfViewPager);
            }

            @Override
            public void failure(Exception e) {
                e.printStackTrace();
            }
        });

Full example available [here](https://github.com/voghDev/PdfViewPager/blob/master/sample/src/main/java/es/voghdev/pdfviewpager/AssetOnSDActivity.java)

Let me know if it helps
