### ISSUE TITLE
Use Remote URL without use of File downloading?

### ISSUE THREAD

**Issue by apollow** [voghDev/PdfViewPager#60]
Is it possible to use the remote URL without downloading and saving to external?

So instead of downloading and saving the file into storage, instead hold that response html content and have it in memory. Using that memory buffer, put it into the PDFViewPager for loading.

**Comment by voghDev** [comment]
Hello,

the library can only read PDF files that are located somewhere in your internal storage or SD card. Reading from another sources is not its purpose, sorry
