### ISSUE TITLE
Annotation, Bookmark And Search Support

### ISSUE THREAD

**Issue by muhammedgunes** [voghDev/PdfViewPager#61]
Do yo support annotation, bookmark and search?

**Comment by apm29** [comment]
same question! does electriconic signatured supported?

**Comment by voghDev** [comment]
Hello,

no, the library only does PDF rendering. No additional operations in the PDF file are supported, such as searching keywords or bookmarking.

About the electronic signature, what do you mean exactly @apm29 ?

**Comment by apm29** [comment]
I mean the Electronic seal add by User, you can see the seal at the end here [http://ding-ccc.oss-cn-hangzhou.aliyuncs.com/contract/FUIOU000088682201801081140556674683.pdf](url)

**Comment by voghDev** [comment]
Well if it's part of the PDF, it should be rendered by the widget. 

Anyway it's not related to `PdfViewPager`, but pdf rendering itself
