### ISSUE TITLE
Fit to Scale

### ISSUE THREAD

**Issue by rainy1106** [voghDev/PdfViewPager#67]
Hi, i am using your library, its working perfectly as i wanted.
I want to Scale Pdf page as Fit to Screen, is there any option to scale page.
Also, can i scroll pdf page vertically.
thank you

**Comment by voghDev** [comment]
Hi,

yes there is, have a look at [PdfPagerAdapter's code](https://github.com/voghDev/PdfViewPager/tree/master/library/src/main/java/es/voghdev/pdfviewpager/library/adapter). In the Builder class, there is a parameter called `PdfScale` that you can use to set the scale.

    public Builder setScale(PdfScale scale) {
            this.scale = scale.getScale();
            this.centerX = scale.getCenterX();
            this.centerY = scale.getCenterY();
            return this;
    }

**Comment by rainy1106** [comment]
Yes, Helped. thanks

**Comment by shabyWoks** [comment]
I have a pdf of width 280px and device screen width of 720px. Here this pdf is not scaling a bit. Pdf shows entire page at once.
