### ISSUE TITLE
How to make it scroll vertically rather than horizontally

### ISSUE THREAD

**Issue by prashantraj** [voghDev/PdfViewPager#7]
Please help me how to make the pdf pages scroll vertically rather than horizontally.

**Comment by voghDev** [comment]
Hello,

PDFViewPager inherits from Android's official ViewPager, so it doesn't support vertical scrolling by default.

The solution would be to do a PDFRecyclerView that can render PDF documents with vertical scrolling. That would be a different widget, not the PDFViewPager.

Hope it helps :)

**Comment by voghDev** [comment]
Hi again, 

I am experimenting an approach to this issue in #31. Take a look if you are still interested.

Thanks!

**Comment by voghDev** [comment]
Hi,

Good news regarding to this issue :) please have a look at the comments in #31. Gonna close this one and we follow discussion there if you don't mind.

**Comment by voghDev** [comment]
Hi,

there is an updated version of the `vertical_viewpager` branch

You can try it using

`implementation 'es.voghdev.pdfviewpager:library:1.1.3'`

Let me know if it's useful for you
