### ISSUE TITLE
PDF rendering failed with same url, that was successfully loaded previously

### ISSUE THREAD

**Issue by sunit09** [voghDev/PdfViewPager#72]
I am opening pdf from a listview item click. After first installation, its working fine for 2 or 3 times with different pdf rendering. after that onSuccess is triggred, but pdf rendering failed, even for the same url that was successfully loaded previously. Max pdf size 300KB.

Please find the log below:
`W/System.err: java.io.IOException: file not in PDF format or corrupted
D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 4096
W/System.err:     at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method)
W/System.err:     at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:166)
W/System.err:     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init(BasePDFPagerAdapter.java:75)
W/System.err:     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.<init>(BasePDFPagerAdapter.java:57)`

**Comment by voghDev** [comment]
True, my bad. Already had this issue fixed in my version of the code, and haven't released yet. Thanks for opening the issue @sunit09. Will release the fix ASAP

**Comment by voghDev** [comment]
Fixed in v1.0.5

    `implementation 'es.voghdev.pdfviewpager:library:1.0.5'`

**Comment by junchenChow** [comment]
in v1.0.5
E/System: java.io.IOException: file not in PDF format or corrupted

url: 
http://huyi-oss-user.oss-cn-shanghai.aliyuncs.com/1_1026443901453451265_1034325014347726849_contract_1535437315336_imgoss1

Once this problem occurs, the PDF after normal loading can not be opened.
