### ISSUE TITLE
Cannot download from URL

### ISSUE THREAD

**Issue by bangtiray** [voghDev/PdfViewPager#73]
how to download using https url?

by the way Good Plugin,

**Comment by voghDev** [comment]
Hello, thank you

You can inherit from `DownloadFile` and create your own implementation that downloads from your HTTPS endpoint. Then use this class with the `RemotePdfViewPager` to perform the download.

Other way is managing the download by yourself outside this library, copy the pdf to the sd card, then open it with a normal `PDFViewPager`

**Comment by bangtiray** [comment]
Hi thanks for advance,, 
solved for download first and getPdfPathOnSDCard
for https not yet solved,, 
thanks
