### ISSUE TITLE
When invalid pdf is rendered, next valid PDFs will never load

### ISSUE THREAD

**Issue by checoalejandro** [voghDev/PdfViewPager#78]
I am using a rest client to receive a PDF, if it comes as invalid (which I don't have a way to check this before), render fails as expected but if I try to load any valid PDFs after the invalid one, render will always fail for any.

**Comment by zxsr20** [comment]
i also meet this problem

**Comment by voghDev** [comment]
Hi guys,

I haven't been able to reproduce this issue. Have you tried closing the invalid PDF before loading the new one? This way you make sure that all resources are freed and resources are erased.
