### ISSUE TITLE
Cannot change background color of PDFViewPager

### ISSUE THREAD

**Issue by EarlyWild** [voghDev/PdfViewPager#90]
I would like it if it was possible to change the background color of the PDFViewPager for the area surrounding the Pdf. For example if my PDFViewPager is defined as a square and the Pdf being drawn is in letter scale, the area around the Pdf should be filled with a background color. Currently, I am unable to visually tell where the pdf borders are located, or the actual size of the Pdf.

**Comment by EarlyWild** [comment]
I figured out that to do this you simply need to override pdfViewPager_background_color to whatever color that is desired.

example:
colors.xml
<resources>
	<color name="pdfViewPager_background_color">#33B5E5</color>
        ....
</resources>

**Comment by EarlyWild** [comment]
Overriding the background color lead to an unexpected result of changing the background of certain PDFs to the overriden color.

**Comment by voghDev** [comment]
This should be faced outside the widget. You can create a plain background with your favorite color, then embed the PdfViewPager inside it with vertical/horizontal margins or similar. If you want a deeper customization of the PDF (like rounded corners on each page, or similar), you can create a custom Adapter class and override the PDF rendering behaviour.

[This example](https://gist.github.com/voghDev/faa5036f076931c8780efe7f53e458a8) uses another library instead of PhotoView to allow higher zooming levels. You can use the as inspiration.

**Comment by EarlyWild** [comment]
I do not think that this will solve my problem. I am using the PdfViewPager to display documents that are to be printed so they have to be as precise as possible. I solved my issue by doing the following...

I modified the view_pdf_page.xml changing the layout_width and layout_height to wrap_content, adding a background color, setting a center gravity and setting adjustViewBounds to true. This way it will give control of the background color of the frame, wrap the pdf to fit properly while centering it, and the adjustViewBounds gets rid of any unwanted padding (You can see how extra padding is added if you change the color of ImageView to something other than white then load a Pdf). Final layout is as follows:

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/pdf_page_container"
    android:layout_width="match_parent" android:layout_height="match_parent"
    android:background="@color/pdfViewPager_background_color">
    <ImageView
        android:id="@+id/imageView"
        android:background="@color/pdfViewPager_background_color_inside"
        android:layout_gravity="center"
        android:adjustViewBounds="true"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
</FrameLayout>`

**Comment by voghDev** [comment]
Looks good :) Overriding the layout and the rendering method inside PdfPagerAdapter is one of the purposes of the library. I'm glad you could adapt it to suit your needs.
